import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { Case } from '../types/db';

/**
 * Generates HTML content for the front label sticker.
 */
export function getFrontLabelHtml(caseData: Case, qrBase64: string): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Front Label - ${caseData.file_number}</title>
      <style>
        body {
          font-family: 'Courier New', Courier, monospace;
          margin: 0;
          padding: 20px;
          display: flex;
          justify-content: center;
          align-items: center;
          background-color: #ffffff;
        }
        .label-container {
          border: 4px double #000000;
          padding: 24px;
          width: 380px;
          box-sizing: border-box;
          text-align: center;
          background: #ffffff;
        }
        .header {
          font-size: 22px;
          font-weight: bold;
          margin-bottom: 2px;
          letter-spacing: 0.5px;
        }
        .divider {
          border-bottom: 3px double #000000;
          margin: 12px 0;
          width: 100%;
        }
        .info-section {
          text-align: left;
          margin-bottom: 12px;
        }
        .label-title {
          font-size: 11px;
          font-weight: bold;
          text-transform: uppercase;
          color: #333333;
          margin: 0 0 2px 0;
        }
        .label-value {
          font-size: 16px;
          font-weight: bold;
          color: #000000;
          margin: 0 0 10px 0;
          line-height: 1.2;
        }
        .qr-section {
          margin-top: 16px;
          display: flex;
          flex-direction: column;
          align-items: center;
        }
        .qr-image {
          width: 130px;
          height: 130px;
          border: 1px solid #000000;
          padding: 4px;
        }
        .qr-caption {
          font-size: 10px;
          margin-top: 4px;
          font-weight: bold;
        }
        .footer {
          margin-top: 16px;
          font-size: 9px;
          font-weight: bold;
          letter-spacing: 1.5px;
          color: #444444;
          text-transform: uppercase;
          border-top: 1px dashed #000000;
          padding-top: 8px;
          width: 100%;
        }
      </style>
    </head>
    <body>
      <div class="label-container">
        <div class="header">FILE NO: ${caseData.file_number}</div>
        <div class="divider"></div>
        
        <div class="info-section">
          <div class="label-title">Client Name:</div>
          <div class="label-value">${caseData.client_name} ${caseData.client_phone ? `(${caseData.client_phone})` : ''}</div>
          
          <div class="label-title">Case details:</div>
          <div class="label-value">${caseData.case_number} (${caseData.case_type})</div>

          <div class="label-title">Advocate Name:</div>
          <div class="label-value">${caseData.advocate_name || 'N/A'}</div>
          
          <div class="label-title">Court Name:</div>
          <div class="label-value">${caseData.court_name || 'N/A'}</div>

          <div class="label-title">Opposite Party:</div>
          <div class="label-value">${caseData.opposite_party || 'N/A'}</div>

          ${caseData.respondent_category ? `
            <div class="label-title">Respondent Category:</div>
            <div class="label-value">${caseData.respondent_category}</div>
          ` : ''}
          
          <div class="label-title">Office Location (Rack / Shelf):</div>
          <div class="label-value">RACK ${caseData.rack_number || 'N/A'} • SHELF ${caseData.shelf_number || 'N/A'}</div>
        </div>
        
        <div class="divider"></div>
        
        <div class="qr-section">
          <img class="qr-image" src="${qrBase64}" />
          <div class="qr-caption">* SCAN TO LOCATE RECORD *</div>
        </div>

        <div class="footer">
          Generated by NyayaRack
        </div>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generates HTML content for the spine label sticker.
 */
export function getSpineLabelHtml(caseData: Case): string {
  // Extract sequence number (the last digits of the file number)
  const fileParts = caseData.file_number.split('-');
  const seqNumber = fileParts[fileParts.length - 1];

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Spine Label - ${caseData.file_number}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 40px;
          display: flex;
          justify-content: center;
          align-items: center;
          background-color: #ffffff;
        }
        .spine-container {
          border: 3px solid #000000;
          padding: 24px 16px;
          width: 200px;
          text-align: center;
          background: #ffffff;
          box-sizing: border-box;
        }
        .sequence-text {
          font-size: 36px;
          font-weight: bold;
          letter-spacing: 2px;
          margin: 0;
          padding-bottom: 12px;
        }
        .location-text {
          font-size: 14px;
          font-weight: bold;
          border-top: 2px solid #000000;
          padding-top: 12px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
      </style>
    </head>
    <body>
      <div class="spine-container">
        <div class="sequence-text">${seqNumber}</div>
        <div class="location-text">RACK ${caseData.rack_number || 'N/A'}<br/>SHELF ${caseData.shelf_number || 'N/A'}</div>
      </div>
    </body>
    </html>
  `;
}

/**
 * Prints the front label sticker for a physical legal file folder.
 * 
 * @param caseData Case record details
 * @param qrBase64 Base64 image data URI of the QR code
 */
export async function printFrontLabel(caseData: Case, qrBase64: string): Promise<void> {
  const htmlContent = getFrontLabelHtml(caseData, qrBase64);
  try {
    await Print.printAsync({
      html: htmlContent,
    });
  } catch (error) {
    console.error('Error printing front label:', error);
    throw error;
  }
}

/**
 * Prints the vertical/spine sticker for a legal file folder.
 * 
 * @param caseData Case record details
 */
export async function printSpineLabel(caseData: Case): Promise<void> {
  const htmlContent = getSpineLabelHtml(caseData);
  try {
    await Print.printAsync({
      html: htmlContent,
    });
  } catch (error) {
    console.error('Error printing spine label:', error);
    throw error;
  }
}

/**
 * Generates and shares the front label as a PDF file.
 */
export async function shareFrontLabel(caseData: Case, qrBase64: string): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing is not available on this device');
  }

  const htmlContent = getFrontLabelHtml(caseData, qrBase64);
  try {
    // Generate PDF to temporary location
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    // Create a user-friendly name for the PDF
    const cleanFileName = `Front_Label_${caseData.file_number.replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`;
    const newUri = `${FileSystem.cacheDirectory}${cleanFileName}`;
    
    // Copy/move the file to cached directory with the user-friendly name
    await FileSystem.moveAsync({
      from: uri,
      to: newUri,
    });

    await Sharing.shareAsync(newUri, {
      mimeType: 'application/pdf',
      dialogTitle: `Share Front Label ${caseData.file_number}`,
      UTI: 'com.adobe.pdf',
    });
  } catch (error) {
    console.error('Error sharing front label PDF:', error);
    throw error;
  }
}

/**
 * Generates and shares the spine label as a PDF file.
 */
export async function shareSpineLabel(caseData: Case): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing is not available on this device');
  }

  const htmlContent = getSpineLabelHtml(caseData);
  try {
    // Generate PDF to temporary location
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    // Create a user-friendly name for the PDF
    const cleanFileName = `Spine_Label_${caseData.file_number.replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`;
    const newUri = `${FileSystem.cacheDirectory}${cleanFileName}`;
    
    // Copy/move the file to cached directory with the user-friendly name
    await FileSystem.moveAsync({
      from: uri,
      to: newUri,
    });

    await Sharing.shareAsync(newUri, {
      mimeType: 'application/pdf',
      dialogTitle: `Share Spine Label ${caseData.file_number}`,
      UTI: 'com.adobe.pdf',
    });
  } catch (error) {
    console.error('Error sharing spine label PDF:', error);
    throw error;
  }
}

/**
 * Generates HTML content for a page (or pages) containing multiple front labels (8 per page in a 2x4 grid).
 */
export function getMultiFrontLabelHtml(selectedCases: { caseData: Case; qrBase64: string }[]): string {
  const pages: string[] = [];
  const labelsPerPage = 8;
  
  for (let i = 0; i < selectedCases.length; i += labelsPerPage) {
    const pageCases = selectedCases.slice(i, i + labelsPerPage);
    
    const labelItemsHtml = pageCases.map(item => {
      const c = item.caseData;
      return `
        <div class="label-box">
          <div class="label-header">FILE NO: ${c.file_number}</div>
          <div class="label-divider"></div>
          <div class="label-content-row">
            <div class="label-info">
              <div class="label-field"><strong>Client:</strong> ${c.client_name}</div>
              <div class="label-field"><strong>Case:</strong> ${c.case_number} (${c.case_type})</div>
              <div class="label-field"><strong>Adv:</strong> ${c.advocate_name || 'N/A'}</div>
              <div class="label-field"><strong>Litigants:</strong> vs ${c.party2 || c.opposite_party || 'N/A'}</div>
              ${c.respondent_category ? `<div class="label-field"><strong>Resp Cat:</strong> ${c.respondent_category}</div>` : ''}
              <div class="label-field"><strong>Location:</strong> RACK ${c.rack_number || 'N/A'} • SHELF ${c.shelf_number || 'N/A'}</div>
            </div>
            <div class="label-qr-sec">
              <img class="label-qr-img" src="${item.qrBase64}" />
              <div class="label-qr-caption">SCAN TO LOCATE</div>
            </div>
          </div>
          <div class="label-footer">Generated by NyayaRack</div>
        </div>
      `;
    }).join('');
    
    pages.push(`
      <div class="page">
        <div class="grid-container">
          ${labelItemsHtml}
        </div>
      </div>
    `);
  }
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>NyayaRack Multi Labels</title>
      <style>
        @page {
          size: A4;
          margin: 0;
        }
        body {
          font-family: 'Courier New', Courier, monospace;
          margin: 0;
          padding: 0;
          background-color: #ffffff;
        }
        .page {
          width: 210mm;
          height: 297mm;
          box-sizing: border-box;
          padding: 10mm;
          page-break-after: always;
        }
        .grid-container {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          grid-template-rows: repeat(4, 1fr);
          gap: 6mm;
          height: 100%;
          width: 100%;
          box-sizing: border-box;
        }
        .label-box {
          border: 2px double #000000;
          padding: 10px;
          height: 64mm;
          box-sizing: border-box;
          text-align: center;
          background: #ffffff;
          display: flex;
          flex-direction: column;
          justify-content: space-between;
        }
        .label-header {
          font-size: 14px;
          font-weight: bold;
          letter-spacing: 0.5px;
        }
        .label-divider {
          border-bottom: 2px double #000000;
          margin: 4px 0;
        }
        .label-content-row {
          display: flex;
          flex-direction: row;
          align-items: center;
          justify-content: space-between;
          flex-grow: 1;
          overflow: hidden;
        }
        .label-info {
          text-align: left;
          font-size: 8.5px;
          line-height: 1.25;
          flex: 1.4;
          padding-right: 4px;
        }
        .label-field {
          margin-bottom: 2px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .label-qr-sec {
          flex: 0.8;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
        }
        .label-qr-img {
          width: 128px;
          height: 128px;
          border: 1px solid #000000;
          padding: 2px;
        }
        .label-qr-caption {
          font-size: 7px;
          font-weight: bold;
          margin-top: 2px;
        }
        .label-footer {
          margin-top: 4px;
          font-size: 7px;
          font-weight: bold;
          letter-spacing: 1px;
          color: #444444;
          text-transform: uppercase;
          border-top: 1px dashed #000000;
          padding-top: 2px;
        }
      </style>
    </head>
    <body>
      ${pages.join('')}
    </body>
    </html>
  `;
}

/**
 * Prints the sheet of front labels (8 per page).
 */
export async function printMultiFrontLabels(selectedCases: { caseData: Case; qrBase64: string }[]): Promise<void> {
  const htmlContent = getMultiFrontLabelHtml(selectedCases);
  try {
    await Print.printAsync({
      html: htmlContent,
    });
  } catch (error) {
    console.error('Error printing multi front labels:', error);
    throw error;
  }
}

/**
 * Generates and shares a sheet of front labels (8 per page) as a PDF file.
 */
export async function shareMultiFrontLabels(selectedCases: { caseData: Case; qrBase64: string }[]): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing is not available on this device');
  }

  const htmlContent = getMultiFrontLabelHtml(selectedCases);
  try {
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    const cleanFileName = `NyayaRack_Labels_Sheet_${Date.now()}.pdf`;
    const newUri = `${FileSystem.cacheDirectory}${cleanFileName}`;
    
    await FileSystem.moveAsync({
      from: uri,
      to: newUri,
    });

    await Sharing.shareAsync(newUri, {
      mimeType: 'application/pdf',
      dialogTitle: `Share Labels Sheet`,
      UTI: 'com.adobe.pdf',
    });
  } catch (error) {
    console.error('Error sharing multi front labels PDF:', error);
    throw error;
  }
}

